[versions]
min-sdk = "31"
compile-sdk = "36"
target-sdk = "36"
jdk = "21"
agp = "8.13.0"
kotlin = "2.2.20"
kotlinx-coroutines = "1.10.2"
google-hilt = "2.57.1"
google-ksp = "2.2.20-2.0.3"
google-material = "1.13.0"
androidx-activity = "1.11.0"
androidx-compose = "1.9.1"
androidx-compose-material3 = "1.3.2"
androidx-core-splashscreen = "1.0.1"
androidx-fragment = "1.8.9"
androidx-hilt = "1.3.0"
androidx-navigation = "2.9.4"

[libraries]
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }
google-hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "google-hilt" }
google-hilt-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "google-hilt" }
google-material = { module = "com.google.android.material:material", version.ref = "google-material" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "androidx-compose-material3" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "androidx-compose" }
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "androidx-core-splashscreen" }
androidx-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "androidx-hilt" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
google-hilt = { id = "com.google.dagger.hilt.android", version.ref = "google-hilt" }
google-ksp = { id = "com.google.devtools.ksp", version.ref = "google-ksp" }