[versions]
min-sdk = "31"
compile-sdk = "36"
target-sdk = "36"
jdk = "21"
agp = "8.13.1"
kotlin = "2.2.21"
kotlinx-coroutines = "1.10.2"
google-hilt = "2.57.2"
google-ksp = "2.3.3"
google-material = "1.13.0"
androidx-activity = "1.12.0"
androidx-compose-material3 = "1.4.0"
androidx-core-splashscreen = "1.2.0"
androidx-hilt = "1.3.0"
gms-services = "4.4.4"
hms-services = "1.9.3.302"
google-analytics = "22.5.0"
huawei-analytics = "6.12.0.301"

[libraries]
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }
google-hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "google-hilt" }
google-hilt-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "google-hilt" }
google-material = { module = "com.google.android.material:material", version.ref = "google-material" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "androidx-compose-material3" }
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "androidx-core-splashscreen" }
androidx-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "androidx-hilt" }
google-firebase-analytics-ktx = { module = "com.google.firebase:firebase-analytics-ktx", version.ref = "google-analytics" }
huawei-hianalytics = { module = "com.huawei.hms:hianalytics", version.ref = "huawei-analytics" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
google-hilt = { id = "com.google.dagger.hilt.android", version.ref = "google-hilt" }
google-ksp = { id = "com.google.devtools.ksp", version.ref = "google-ksp" }
google-services = { id = "com.google.gms.google-services", version.ref = "gms-services" }
huawei-services = { id = "com.huawei.agconnect", version.ref = "hms-services" }